:experimental:
= Messaging stack on-boarding

NOTE: This is a work in progress document

This documentation is designed as a walk-through to onboard users to the ABC-RP messaging stack.
It will demonstrate an exemplary onboarding process as well as linking to further reading regarding the APIs and standards employed.

Efforts have been made to link to rather than duplicate other documentation.

== Overview

The ABC messaging stack is based on the following projects and standards:

* link:https://mqtt.org/[MQTT] (Network protocol)
* link:https://www.eclipse.org/hono/[Eclipse Hono] (API definitions)
* link:https://github.com/theodi/BDNS[Building Device Naming Standards initiative (BDNS)] project (Device naming)
* link:https://brickschema.org/[Brick Schema] (Point naming)
* link:https://github.com/faucetsdn/udmi[UDMI] (Payload format)

=== Contributing

This document should comply with the link:https://github.com/abc-rp/styleguide#documentation[ABC-RP styleguide] for documentation.

== Pre-requisites

=== Command line tools

The usual command line tools:

* [command]`hono-cli` - aka link:https://www.eclipse.org/hono/downloads/[Hono command line client]
* [command]`hat` - aka link:https://github.com/ctron/hat[Hono Admin Tool]
* [command]`http` - aka link:https://httpie.org/[HTTPie]
* [command]`mqtt` - aka link:https://github.com/hivemq/mqtt-cli[MQTT CLI]


== Concepts

When registering devices there are a number of details that you need to know:

* Network Hostnames
* Your Tenant ID
* Device IDs
* Credentials

=== Network Hostnames

You will need to know the domain names and ports used by the ABC-RP infrastructure so that you can register your devices and have them communicate with the stack.
These will be provided by ABC-RP as part of your onboarding information.
Example values are shown below:

* `registry.facilities.abc-rp.com:28080` Device Registration
* `mqtt.facilities.abc-rp.com:1883` Devices connecting to MQTT Protocol Adapter
* `amqp.facilities.abc-rp.com:15671` Client applications consuming data

=== Tenant ID

link:https://www.eclipse.org/hono/docs/1.4/concepts/tenancy/[Hono Multi-Tenancy]

link:https://www.eclipse.org/hono/docs/1.4/api/tenant/[Tenant API Specification]

You will be provided a Tenant ID as part of your onboarding information.
This is used internally to manage data and data streams into strictly isolated subsets.  

An example Tenant ID might be:

* `swansea.iot`

=== Device ID

link:https://www.eclipse.org/hono/docs/1.4/concepts/device-identity/[Hono Device Identity]

link:https://www.eclipse.org/hono/docs/1.4/api/device-registration/[Device Registration API Specification]

link:https://github.com/theodi/BDNS[Building Device Naming Standards initiative (BDNS)]


Device naming should follow the emerging [acronym]`BDNS` standard.
The specification can be found on this link:https://github.com/theodi/BDNS/blob/master/BDNS_Specification_naming_syntax.md[Github page].
Also follow the current link:https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv[Abbreviations Register].

NOTE: Check the link:https://github.com/theodi/BDNS/branches[development branches] for the latest abbreviations

All devices should have a Device ID even if their communication is handled by a Device Gateway.
The optional prefix is strongly encouraged.

Example Device IDs:

* `GB-LON-BLD2_TSTAT-1` First thermostat in the UK, London, building `BLD2`.
* `JE-JE3-BLD1_TPS-75` Seventy fifth temperature sensor in Jersey, postcode district 3, building `BLD1`

An optional suffix can also be used as required.

* `GB-LON-BLD2_TSTAT-1_RH-2-3-25-CO2` 

=== Device Gateway

link:https://www.eclipse.org/hono/docs/1.4/concepts/connecting-devices/#connecting-via-a-device-gateway[Connecting via a Device Gateway]

The most straightforward scenario is a device connecting to one of Hono’s protocol adapters directly via IP based network infrastructure.
For this to work, the device needs to use a supported communication protocol. For the ABC-RP stack MQTT is recommended.

In some cases, a device may not be able to directly connect to one of Hono’s protocol adapters. An example is a device that uses a serial bus or radio waves for local communication. Such devices can be connected to a protocol adapter by means of a device gateway which acts on behalf of the device(s) when communicating with Hono.

Device Gateways have the `BDNS` abbreviation `CGW`.
For example:

 * `GB-LON-BLD2_CGW-1` First Device Gateway in the UK, London, building `BLD2`.

This gateway, for example, may handle communications for the `GB-LON-BLD2_TSTAT-1` sensor mentioned above.

When creating and modifying Device Gateways they are treated in exactly the same way as Devices.

=== Credentials

link:https://www.eclipse.org/hono/docs/1.4/concepts/device-identity/#device-authentication[Device Authentication]

link:https://www.eclipse.org/hono/docs/1.4/api/credentials/[Credentials API Specification]

After registering a new device (or gateway), you must set the user name and password credentials for the device to authenticate with the server.

The Credentials API supports registration of multiple sets of credentials for each device.
A device may be authenticated using different types of secrets, e.g. a `hashed password` or a `pre-shared key`, depending on the capabilities of the device and/or protocol adapter.

=== Point naming

link:https://brickschema.org/[Brick Schema]

Each of the devices that we have created will publish various data points.

The naming for these data points should refer to the link:https://brickschema.org/[Brick Schema].

NOTE: The link:https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv[BDNS register] references appropriate Brick classes for different asset types.

For a `TPS` temperature sensor device we may use Brick data point names from the link:https://brickschema.org/ontology/1.1/classes/Air_Temperature_Sensor[Air Temperature Sensor] subclass of:

* `supply_air_temperature_sensor`
* `zone_air_temperature_sensor`
* `return_air_temperature_sensor`

=== Payload

link:https://github.com/faucetsdn/udmi[UDMI]

When we have identified the point names for our device we need to encode them into a `json` payload.

To do this we will follow the link:https://github.com/faucetsdn/udmi[UDMI] Schema.

TIP: Arup provides a useful helper library link:https://github.com/arupiot/pyudmi[pyudmi] for working with UDMI objects in python.

An example payload for our Jersey temperature sensor `JE-JE3-BLD1_TPS-75` using the above point names may look something like the below:

[source,json]
----
{
  "version": 1,
  "timestamp": "2019-01-17T14:02:29.364Z",
  "points": {
    "supply_air_temperature_sensor": {
      "present_value": 20.30108642578125
    },
    "zone_air_temperature_sensor": {
      "present_value": 17.23421412344333
    },
    "return_air_temperature_sensor": {
      "present_value": 18.23423567344323
    }
  }
}
----

NOTE: If developing a Device Gateway you would construct a separate payload for each child device that the gateways communicates on behalf of. 

== Example

link:https://www.eclipse.org/hono/getting-started/[Hono Getting started]

NOTE: The commands below are prefixed with the `$` character which represent the command prompt and should not be copied.
The output of the command may also be shown below.

NOTE: All of the commands that use HTTPie's `http` are communicating with HTTP APIs and can be communicated with using any tools that work with HTTP.
For example if working with `python` you may use the link:https://requests.readthedocs.io/en/master/[Requests library].

=== Setup environment variables for Hostnames

If using a shell environment like link:https://www.gnu.org/software/bash/[bash] you can set up environment variables to reuse in later commands:

[source,bash]
----
$ export REGISTRY_IP=registry.facilities.abc-rp.com
$ export MQTT_ADAPTER_IP=mqtt.facilities.abc-rp.com
$ export AMQP_NETWORK_IP=amqp.facilities.abc-rp.com
----

=== Creating a new Tenant

You will receive a tenantId value from ABC-RP.
Set it up as an environment variable:

[source,bash]
----
$ export MY_TENANT=swansea.iot
----

NOTE: It is likely that this next process has been done for you so you can skip to Adding a Device to the Tenant.


Register a tenant using Hono’s Device Registry’s management HTTP API:

[source,bash]
----
$ http --form POST http://$REGISTRY_IP:28080/v1/tenants/$MY_TENANT

HTTP/1.1 201 Created
content-length: 20
content-type: application/json; charset=utf-8
etag: fb52545d-1252-4c68-baf1-138964a111a4
location: /v1/tenants/swansea.iot

{
    "id": "swansea.iot"
}
----

=== Adding a Device to the Tenant

IMPORTANT: Rather than setting the device ID to the `BDNS` id we could let hono generate a UUID and include the `BDNS` id as metadata.

Register a device using Hono’s Device Registry’s management HTTP API:

[source,bash]
----
$ export MY_DEVICE=JE-JE3-BLD1_TPS-75
----

[source,bash]
----
$ http --form POST http://$REGISTRY_IP:28080/v1/devices/$MY_TENANT/$MY_DEVICE
HTTP/1.1 201 Created
content-length: 27
content-type: application/json; charset=utf-8
etag: 24928f75-262d-4609-a03c-44831afc4acb
location: /v1/devices/swansea.iot/JE-JE3-BLD1_TPS-75

{
    "id": "JE-JE3-BLD1_TPS-75"
}
----

=== Setting a Password for the Device

[source,bash]
----
$ export MY_PWD=my-pwd
$ echo '[{        
  "type": "hashed-password",
  "auth-id": "'$MY_DEVICE'",
  "secrets": [{
      "pwd-plain": "'$MY_PWD'"
  }]
}]' | http PUT http://$REGISTRY_IP:28080/v1/credentials/$MY_TENANT/$MY_DEVICE

HTTP/1.1 204 No Content
content-type: application/json; charset=utf-8
etag: 5d3b8b7a-9700-45d2-809b-6e2613c82cba
----

== Starting the example Application

The client can then be started from the command line as follows:

[source,bash]
----
# in directory where the hono-cli-*-exec.jar file has been downloaded to
$ java -jar hono-cli-*-exec.jar \
  --hono.client.host=$AMQP_NETWORK_IP \
  --hono.client.port=15672 \
  --hono.client.username=consumer@HONO \
  --hono.client.password=verysecret \
  --spring.profiles.active=receiver \
  --tenant.id=$MY_TENANT
----

== Publishing Data to the MQTT Adapter

=== Publishing Telemetry Data to the MQTT Adapter

Now that the downstream application is running, devices can start publishing telemetry data and events using Hono’s protocol adapters.

We will be using the UDMI payload schema so will need to serialising timestamps accordingly.  To generate such an example timestamps in bash run the following code@

[source,bash]
----
$ TZ='UTC' date --iso-8601='ns' | sed -e 's/+00:00//g' | sed -e 's/,/./g' | awk '{print $1"Z"}'
2020-11-16T17:35:56.747500374Z
----

NOTE: For an example of serialising timestamps in `python` review `pyudmi`'s link:https://github.com/arupiot/pyudmi/blob/0.0.3/src/udmi/base.py#L73[serialise_timestamp] function.

Now we have a timestamp we can create a simulated payload for our device and send it over the MQTT protocol:

[source,bash]
----
$ mqtt pub -V 3 -h $MQTT_ADAPTER_IP -t telemetry \
  -u $MY_DEVICE@$MY_TENANT -pw $MY_PWD -m '{
  "version": 1,
  "timestamp": 2020-11-16T17:35:56.747500374Z,
  "points": {
    "supply_air_temperature_sensor": {
      "present_value": 20.30108642578125
    },
    "zone_air_temperature_sensor": {
      "present_value": 17.23421412344333
    },
    "return_air_temperature_sensor": {
      "present_value": 18.23423567344323
    }
  }
}'
----

If you have started the downstream `hono-cli` application as described in the previous section, you should now see the telemetry message being logged to the application’s console in the other terminal. The output should look something like this:

[source,bash]
----
17:36:11.165 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - received telemetry message [device: JE-JE3-BLD1_TPS-75, content-type: application/octet-stream]: {
  "version": 1,
  "timestamp": 2020-11-16T17:35:56.747500374Z,
  "points": {
    "supply_air_temperature_sensor": {
      "present_value": 20.30108642578125
    },
    "zone_air_temperature_sensor": {
      "present_value": 17.23421412344333
    },
    "return_air_temperature_sensor": {
      "present_value": 18.23423567344323
    }
  }
}
17:36:11.165 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - ... with application properties: {orig_adapter=hono-mqtt, device_id=JE-JE3-BLD1_TPS-75, qos=0, orig_address=telemetry}
----

=== Publishing Events to the MQTT Adapter

In a similar way you can upload events:

[source,bash]
----
$ mqtt pub -V 3 -h $MQTT_ADAPTER_IP -t event \
  -u $MY_DEVICE@$MY_TENANT -pw $MY_PWD -q 1 -m '{
  "version": 1,
  "timestamp": 2020-11-16T17:36:37.140545700Z,
  "points": {
    "co2_alarm": {
      "present_value": true
    }
  }
}'
----


[source,bash]
----
17:36:46.669 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - received event message [device: JE-JE3-BLD1_TPS-75, content-type: application/octet-stream]: {
  "version": 1,
  "timestamp": 2020-11-16T17:36:37.140545700Z,
  "points": {
    "co2_alarm": {
      "present_value": true
    }
  }
}
17:36:46.669 [vert.x-eventloop-thread-0] INFO  org.eclipse.hono.cli.app.Receiver - ... with application properties: {orig_adapter=hono-mqtt, device_id=JE-JE3-BLD1_TPS-75, qos=1, orig_address=event}
----